/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author juanc
 */
public class frmCliente extends javax.swing.JFrame {

    /**
     * Creates new form frmCliente
     */
    public frmCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipoId = new javax.swing.ButtonGroup();
        txtClienteFecha = new javax.swing.JTextField();
        txtClienteHistoriaNo = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        txtClienteFecha1 = new javax.swing.JTextField();
        txtClienteFecha2 = new javax.swing.JTextField();
        txtClienteFecha3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtClienteFecha4 = new javax.swing.JTextField();
        txtClienteFecha5 = new javax.swing.JTextField();
        txtClienteFecha6 = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 490));
        getContentPane().setLayout(null);
        getContentPane().add(txtClienteFecha);
        txtClienteFecha.setBounds(100, 120, 150, 20);
        getContentPane().add(txtClienteHistoriaNo);
        txtClienteHistoriaNo.setBounds(410, 120, 100, 20);

        btnGroupTipoId.add(jRadioButton1);
        jRadioButton1.setText("C.C.");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(50, 150, 47, 23);
        getContentPane().add(txtClienteFecha1);
        txtClienteFecha1.setBounds(190, 150, 150, 20);
        getContentPane().add(txtClienteFecha2);
        txtClienteFecha2.setBounds(380, 150, 50, 20);
        getContentPane().add(txtClienteFecha3);
        txtClienteFecha3.setBounds(120, 170, 180, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero/a", "Casado/a", "Divorciado/a", "Separado/a", "Viudo/a", "Union Libre", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(350, 200, 200, 20);
        getContentPane().add(txtClienteFecha4);
        txtClienteFecha4.setBounds(380, 170, 170, 20);
        getContentPane().add(txtClienteFecha5);
        txtClienteFecha5.setBounds(120, 200, 180, 20);
        getContentPane().add(txtClienteFecha6);
        txtClienteFecha6.setBounds(470, 150, 80, 20);

        btnGroupTipoId.add(jRadioButton2);
        jRadioButton2.setText("C.E.");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(140, 150, 50, 23);

        btnGroupTipoId.add(jRadioButton3);
        jRadioButton3.setText("T.I.");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(100, 150, 43, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(110, 230, 130, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(310, 230, 40, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG_CrearCliente.png"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(450, 600));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 600, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupTipoId;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtClienteFecha;
    private javax.swing.JTextField txtClienteFecha1;
    private javax.swing.JTextField txtClienteFecha2;
    private javax.swing.JTextField txtClienteFecha3;
    private javax.swing.JTextField txtClienteFecha4;
    private javax.swing.JTextField txtClienteFecha5;
    private javax.swing.JTextField txtClienteFecha6;
    private javax.swing.JTextField txtClienteHistoriaNo;
    // End of variables declaration//GEN-END:variables
}
